trigger:
  branches:
    include:
      - main

# ============================================================
# Cross-repository resource declarations
#
# HOW TO TEST THIS LOCALLY:
#
# 1. Copy the "samples" folder from this repo to sit NEXT TO
#    the extension repo, and name it "azure-pipeline-samples":
#
#    _projects/
#    ├── azure-templates-vscode-extension/   ← this repo (open in VS Code)
#    └── azure-pipeline-samples/             ← copy of samples/ folder
#        ├── templates/
#        │   ├── build-dotnet.yml
#        │   └── ...
#        └── stages/
#            └── deploy-stage.yml
#
# 2. Open this file in VS Code and hover over any "@templates" line below.
#    The extension will resolve the template from the sibling folder.
#
# The folder name ("azure-pipeline-samples") must match the last segment
# of the "name:" field in the repository entry below.
# ============================================================
resources:
  repositories:
    - repository: templates
      type: git
      name: myorg/azure-pipeline-samples
      ref: refs/heads/main

stages:
  # ============================================================
  # BUILD STAGE — template lives in the "templates" external repo
  # Resolved to: {_projects}/../azure-pipeline-samples/templates/build-dotnet.yml
  # Hover over the line below to see the template parameters!
  # ============================================================
  - template: templates/build-dotnet.yml@templates
    parameters:
      project: '**/*.csproj'
      buildConfiguration: Release
      dotnetVersion: '8.0.x'
      publishArtifact: true

  # ============================================================
  # DEPLOY STAGE — also from the external repo
  # Resolved to: {_projects}/../azure-pipeline-samples/stages/deploy-stage.yml
  # ============================================================
  - template: stages/deploy-stage.yml@templates
    parameters:
      environment: Production
      azureSubscription: Azure-Prod-ServiceConnection
      appName: myapp-prod-webapp
      dependsOn:
        - Build
